### ISSUE TITLE
M5 Core 2 - Arduino board issue

### ISSUE THREAD

**Issue by thadius83** [m5stack/M5Core2#162]
Hi All,

My M5Core2 library fails compiling with
pngle.c:31:10: fatal error: rom/miniz.h: No such file or directory
31 | #include <rom/miniz.h>
| ^~~~~~~~~~~~~
compilation terminated.

Using 2.3.6 arduino ide and latest library (both with M5Stck and ESP Board jsons). I had blank code with just the library and it failed.

reverting back to 2.14 on the M5Stack version resolves the issue.

**Comment by thadius83** [comment]
> Core2 can only be used with the M5Core2 repository, please refer to this [document](https://docs.m5stack.com/en/arduino/m5core2/program).
@Tinyu-Zhao which is precisely what I’m doing. 

I have version 0.2.0 of the m5core2 library installed

When I update the m5 board definition from 2.1.4 to 3.2, that’s where the issues occur.

**Comment by thadius83** [comment]
so you're saying to use

`#include <M5Unified.h>`

instead of 

`#include <M5Core2.h>`
 
?

I'll try that out when I'm home on version 3.2 of the M5 Board.
